/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 7
#define LARGE_STATE_COUNT 6
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 2
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_fmod = 2,
  anon_sym_endfm = 3,
  anon_sym_mod = 4,
  anon_sym_endm = 5,
  anon_sym_op = 6,
  anon_sym_sort = 7,
  anon_sym_eq = 8,
  anon_sym_rl = 9,
  anon_sym_is = 10,
  anon_sym_Nat = 11,
  anon_sym_Bool = 12,
  sym_other = 13,
  sym_source_file = 14,
  sym__token = 15,
  sym_keyword = 16,
  sym_base_type = 17,
  aux_sym_source_file_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_fmod] = "fmod",
  [anon_sym_endfm] = "endfm",
  [anon_sym_mod] = "mod",
  [anon_sym_endm] = "endm",
  [anon_sym_op] = "op",
  [anon_sym_sort] = "sort",
  [anon_sym_eq] = "eq",
  [anon_sym_rl] = "rl",
  [anon_sym_is] = "is",
  [anon_sym_Nat] = "Nat",
  [anon_sym_Bool] = "Bool",
  [sym_other] = "other",
  [sym_source_file] = "source_file",
  [sym__token] = "_token",
  [sym_keyword] = "keyword",
  [sym_base_type] = "base_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_fmod] = anon_sym_fmod,
  [anon_sym_endfm] = anon_sym_endfm,
  [anon_sym_mod] = anon_sym_mod,
  [anon_sym_endm] = anon_sym_endm,
  [anon_sym_op] = anon_sym_op,
  [anon_sym_sort] = anon_sym_sort,
  [anon_sym_eq] = anon_sym_eq,
  [anon_sym_rl] = anon_sym_rl,
  [anon_sym_is] = anon_sym_is,
  [anon_sym_Nat] = anon_sym_Nat,
  [anon_sym_Bool] = anon_sym_Bool,
  [sym_other] = sym_other,
  [sym_source_file] = sym_source_file,
  [sym__token] = sym__token,
  [sym_keyword] = sym_keyword,
  [sym_base_type] = sym_base_type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_fmod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mod] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endm] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_op] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sort] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_eq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Nat] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bool] = {
    .visible = true,
    .named = false,
  },
  [sym_other] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_base_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(3);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym_other);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(3);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'B', 1,
        'N', 2,
        'e', 3,
        'f', 4,
        'i', 5,
        'm', 6,
        'o', 7,
        'r', 8,
        's', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(12);
      if (lookahead == 'q') ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead == 'm') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 6:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(18);
      END_STATE();
    case 9:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_eq);
      END_STATE();
    case 14:
      if (lookahead == 'o') ADVANCE(23);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_op);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_rl);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(25);
      END_STATE();
    case 20:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_Nat);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(27);
      if (lookahead == 'm') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'd') ADVANCE(29);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_mod);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_Bool);
      END_STATE();
    case 27:
      if (lookahead == 'm') ADVANCE(31);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_endm);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_fmod);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_sort);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_endfm);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_fmod] = ACTIONS(1),
    [anon_sym_endfm] = ACTIONS(1),
    [anon_sym_mod] = ACTIONS(1),
    [anon_sym_endm] = ACTIONS(1),
    [anon_sym_op] = ACTIONS(1),
    [anon_sym_sort] = ACTIONS(1),
    [anon_sym_eq] = ACTIONS(1),
    [anon_sym_rl] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [anon_sym_Nat] = ACTIONS(1),
    [anon_sym_Bool] = ACTIONS(1),
    [sym_other] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(6),
    [sym__token] = STATE(2),
    [sym_keyword] = STATE(2),
    [sym_base_type] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_fmod] = ACTIONS(7),
    [anon_sym_endfm] = ACTIONS(7),
    [anon_sym_mod] = ACTIONS(7),
    [anon_sym_endm] = ACTIONS(7),
    [anon_sym_op] = ACTIONS(7),
    [anon_sym_sort] = ACTIONS(7),
    [anon_sym_eq] = ACTIONS(7),
    [anon_sym_rl] = ACTIONS(7),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_Nat] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [sym_other] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_base_type] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_identifier] = ACTIONS(13),
    [anon_sym_fmod] = ACTIONS(7),
    [anon_sym_endfm] = ACTIONS(7),
    [anon_sym_mod] = ACTIONS(7),
    [anon_sym_endm] = ACTIONS(7),
    [anon_sym_op] = ACTIONS(7),
    [anon_sym_sort] = ACTIONS(7),
    [anon_sym_eq] = ACTIONS(7),
    [anon_sym_rl] = ACTIONS(7),
    [anon_sym_is] = ACTIONS(7),
    [anon_sym_Nat] = ACTIONS(9),
    [anon_sym_Bool] = ACTIONS(9),
    [sym_other] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym__token] = STATE(3),
    [sym_keyword] = STATE(3),
    [sym_base_type] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [anon_sym_fmod] = ACTIONS(20),
    [anon_sym_endfm] = ACTIONS(20),
    [anon_sym_mod] = ACTIONS(20),
    [anon_sym_endm] = ACTIONS(20),
    [anon_sym_op] = ACTIONS(20),
    [anon_sym_sort] = ACTIONS(20),
    [anon_sym_eq] = ACTIONS(20),
    [anon_sym_rl] = ACTIONS(20),
    [anon_sym_is] = ACTIONS(20),
    [anon_sym_Nat] = ACTIONS(23),
    [anon_sym_Bool] = ACTIONS(23),
    [sym_other] = ACTIONS(17),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(26),
    [sym_identifier] = ACTIONS(28),
    [anon_sym_fmod] = ACTIONS(28),
    [anon_sym_endfm] = ACTIONS(28),
    [anon_sym_mod] = ACTIONS(28),
    [anon_sym_endm] = ACTIONS(28),
    [anon_sym_op] = ACTIONS(28),
    [anon_sym_sort] = ACTIONS(28),
    [anon_sym_eq] = ACTIONS(28),
    [anon_sym_rl] = ACTIONS(28),
    [anon_sym_is] = ACTIONS(28),
    [anon_sym_Nat] = ACTIONS(28),
    [anon_sym_Bool] = ACTIONS(28),
    [sym_other] = ACTIONS(28),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(30),
    [sym_identifier] = ACTIONS(32),
    [anon_sym_fmod] = ACTIONS(32),
    [anon_sym_endfm] = ACTIONS(32),
    [anon_sym_mod] = ACTIONS(32),
    [anon_sym_endm] = ACTIONS(32),
    [anon_sym_op] = ACTIONS(32),
    [anon_sym_sort] = ACTIONS(32),
    [anon_sym_eq] = ACTIONS(32),
    [anon_sym_rl] = ACTIONS(32),
    [anon_sym_is] = ACTIONS(32),
    [anon_sym_Nat] = ACTIONS(32),
    [anon_sym_Bool] = ACTIONS(32),
    [sym_other] = ACTIONS(32),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(6)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [20] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_base_type, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_base_type, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_maude(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "maude",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
